Readme Updated
ArasLabs/override-default-structure-browser pull request #1
Opened 2019-03-20 19:53 UTC by sampoearas

Tested on 11 SP12, 15

2019-03-22 20:23 UTC, EliJDonahue requested changes

2019-03-22 20:23 UTC, EliJDonahue commented on README.md
> +[v1.0.1](https://github.com/ArasLabs/override-default-structure-browser/releases/tag/v1.0.1) | 10.0 SPx, 11.0 SP7+, 11.0 SP12+, 11.0 SP15
This project works for all v11.0 service packs.
```suggestion
[v1.0.1](https://github.com/ArasLabs/override-default-structure-browser/releases/tag/v1.0.1) | 10.0 SPx, 11.0 SPx
```

2019-03-22 20:56 UTC, sampoearas commented
changes  committed

2019-03-23 02:02 UTC, EliJDonahue approved these changes

2019-03-23 02:02 UTC, merged